version: '3.7'
services:
  backend: # Service Backend
    build:
      ./Backend_API/simple-api-2
    networks:
      - my-network
    depends_on:
      - database # Définition de la priorite de lancement

  database:
    build:
      ./Database # Definition du repertoire vers le dockerfile
    networks:
      - my-network

  httpd:
    build:
      ./Http_Server
    ports:
      - 80:80 # Definition des ports
    networks:
      - my-network
    depends_on:
      - backend

  front:
    container_name: 
      front
    build:
      ./front
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network: # Creation de notre network
