---
# tasks file for roles/app
- name: Run Backend
  docker_container:
    name: backend
    image: charlesboyercpe/backend
    exposed_ports: 
      - 80:80
    state: started
    networks:
      - name: frontend
      - name: backend